### ISSUE TITLE
 Unexpected directive 'CommonComponent' imported by the module...

### ISSUE THREAD

**Issue by andishejavan** [aikeru/Angular2Kendo#2]
Display error when load page .error this is 
` Unexpected directive 'CommonComponent' imported by the module...`

**Comment by aikeru** [comment]
This may have been due to the code I originally wrote based on the alpha of Angular 2.
I have since updated the code for Angular 4.
I will close this issue for now, but if you see an issue with Angular 4 please feel free to open another or comment back on this issue if you like.
